#!/bin/bash

echo "Testing AuricHalo Audio Input"
echo "=============================="
echo ""
echo "1. Open the app (already opened)"
echo "2. In the app, click 'Options' or look for audio settings"
echo "3. Select 'Built-in Microphone' as INPUT device"
echo "4. Make sure Input channels 1-2 are ENABLED (checked)"
echo "5. CLAP your hands or SPEAK LOUDLY"
echo "6. Watch the INPUT METER (left side bars)"
echo ""
echo "Expected: Green/yellow/red LEDs should light up"
echo ""
echo "If NO input:"
echo "  - Check System Settings → Privacy → Microphone"
echo "  - Make sure AuricHalo is allowed"
echo ""
echo "Current audio devices:"
system_profiler SPAudioDataType | grep -A 5 "Built-in"
